//...
BeamUser user = beam.use(UsersService.class).login(username, password).get();
BeamChat chat = beam.use(ChatService.class).findOne(user.channel.id).get();
BeamChatConnectable chatConnectable = chat.connectable(beam);
//...
